### ISSUE TITLE
Let's work together?

### ISSUE THREAD

**Issue by simpletoimplement** [vairogs/vairogs#5]
Hey. You have an awesome library going on here. I have recently started adding my own libraries on github.  
I have small set of functions currently located at my https://github.com/spaghettisolutions/spaghetti repository. Would you mind adding these functions to your library? And I will just require them via composer? This way we can work together on awesome functions and not compete. What do you say?

**Comment by k0d3r1s** [comment]
Hi. Interesting offer. Sure, why not.  
I'm currently doing a small refactoring around functions but I'm sure we can work something out here.  
Best option here would be a PR from you with your functions instead of me just copying them over, don't you think?  
Can you wait a day or two though? I will finish my refactoring and then you do a PR?  

P.S. You have nice libraries as well, I added some to my repos already :)

**Comment by simpletoimplement** [comment]
I can wait, no problem. Maybe just write here when I can make a PR? And I would appreciate if you told me where to put my functions. Like in which namespace or directory? and which package I would need to require with composer?

**Comment by k0d3r1s** [comment]
you can add now :)  
namespace would be Vairogs\Functions, located at src/Vairogs/Functions. Please add tests, I can see that your current library does not have any.  
If all is good and merged, you will be able to access functions by requiring vairogs/functions package
